# -------------------------------------------------------------------------
# 02_run_neb.py
#
# [Function]
# Executes the most computationally expensive NEB synchronous optimization step.
#
# [Files required before running independently]
# (Copy the following files from the directory where 01_prep_wavefunctions.py was executed)
# 1. initial_images.traj
# 2. neb_image_00.chk to neb_image_31.chk (32 files in total)
# -------------------------------------------------------------------------

import ase
import ase.io
import ase.mep
import ase.optimize
import re
from ase.calculators.gaussian import Gaussian
from ase.units import Hartree

class GaussianCASSCF(Gaussian):
    """
    1) Fix the "Blank line reading weights" error caused by an extra empty line before the addsec weights section;
    2) Fix the issue where the default ASE parser cannot read CASSCF energies (it only recognizes 'SCF Done:' / 'Energy=', whereas CASSCF uses the 'EIGENVALUE' format);
    3) Automatically parse the CI root number of the target electronic state from nroot=N in the method (when used with IOp(5/97=100,10/97=100), S1 is shifted to the last
       root position, i.e., root=nroot), no need to pass root manually;
    4) Discard the "Mulliken charges with hydrogens summed into heavy atoms" misread by ASE
       (the length does not match the number of atoms, which causes broadcast errors when
       writing xyz/trajectory).
    """

    def write_input(self, atoms, properties=None, system_changes=None):
        super().write_input(atoms, properties, system_changes)
        fname = self.label + ".com"
        with open(fname) as f:
            content = f.read()
        content = content.replace(
            "\n\n\n" + self.parameters["addsec"],
            "\n\n" + self.parameters["addsec"]
        )
        with open(fname, "w") as f:
            f.write(content)

    def _get_target_root(self):
        method = self.parameters.get("method", "")
        m = re.search(r"nroot\s*=\s*(\d+)", method, re.IGNORECASE)
        if not m:
            raise ValueError(
                "Failed to parse nroot from the method parameter, please check the CASSCF keyword format, "
                "e.g., 'CASSCF(6,5,nroot=3,stateaverage)'"
            )
        return int(m.group(1))

    def read_results(self):
        super().read_results()

        self.results.pop("charges", None)

        root = self._get_target_root()
        pattern = re.compile(r"\(\s*%d\)\s+EIGENVALUE\s+(-?\d+\.\d+)" % root)
        energy_hartree = None
        with open(self.label + ".log") as f:
            for line in f:
                m = pattern.search(line)
                if m:
                    energy_hartree = float(m.group(1))
        if energy_hartree is None:
            raise RuntimeError(
                f"Failed to find CASSCF EIGENVALUE for root={root} in {self.label}.log, "
                "please check if the log contains the 'EIGENVALUES AND EIGENVECTORS OF CI MATRIX' section."
            )
        self.results["energy"] = energy_hartree * Hartree

# === Step 5 (Part B): Run NEB ===

# Read the interpolated configurations generated and saved by the preceding script
images = ase.io.read("initial_images.traj", index=":")

# Attach a calculator to each image (corresponding to the .chk files generated by the preceding script)
for i, image in enumerate(images):
    chk_filename = f"neb_image_{i:02d}.chk"
    
    image_calc = GaussianCASSCF(
            label=f"neb_image_{i:02d}",
            # [Modification 1]: Restore the original format, NO spaces are allowed inside the parentheses!
            method="CASSCF(6,5,nroot=3,stateaverage)", 
            basis="6-31g(d,p)",
            extra=" nosym guess=read IOp(5/97=100,10/97=100)",
            charge=0,
            mult=1,
            mem="32GB",          
            nprocshared=16,       
            output_type="P",
            chk=chk_filename,
            addsec="0.3333333 0.3333333 0.3333333",
            command="module load Gaussian/16.C.02-AVX2 && g16 < PREFIX.com > PREFIX.log"
        )
    image.calc = image_calc

polymer = ase.mep.NEB(images, allow_shared_calculator=False, climb=False, method='improvedtangent')

# Initialize optimizer, configure file output to record evolution trajectory.
neb_opt = ase.optimize.BFGS(polymer, trajectory="S1_NEB_Full_Path.traj")

# === New code block starts ===
def record_step():
    # neb_opt.nsteps is the internal counter of the ASE optimizer, recording the current number of steps
    current_step = neb_opt.nsteps 
    
    # Open the txt file in append mode ('a')
    with open("neb_progress.txt", "a") as f:
        f.write(f"NEB step {current_step} completed successfully.\n")

    # Print the progress to the terminal
    print(f"--- ASE Logger: NEB step {current_step} completed. ---")

# Attach this function to the optimizer. ASE will automatically call record_step after moving atoms in each step
neb_opt.attach(record_step)
# === New code block ends ===

# Execute NEB synchronous optimization to find the transition state.
neb_opt.run(fmax=0.05, steps=500) # do 1 steps first, to see if all orbitals are correct
